"""全局配置常量"""

# LLM 调用
DEFAULT_MAX_TOKENS = 4096
WRITER_MAX_TOKENS = 8192
LLM_TIMEOUT_SEC = 60

# Searcher
SEARCH_MAX_RESULTS = 8
FILTER_BATCH_SIZE = 15
SEARCH_RATE_LIMIT_SEC = 1.5
SEARCH_TIMEOUT_SEC = 30

# Analyzer
ANALYZER_BATCH_SIZE = 5
ABSTRACT_MAX_CHARS = 500

# Organizer
ORGANIZER_MAX_ANALYSES = 30

# Writer
WRITER_MAX_PAPERS = 40

# Reviewer
REVIEW_MAX_CHARS = 20000
